# -*- coding: utf-8 -*-
"""codigo_para_cargar_db flo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tq8gKcKN96ZznMTzRco9zk3ycG9W4kdl
"""

import pandas as pd

#cargar datos
df = pd.read_csv("/content/Florencia_database_limpia.csv", sep=";")

#Echar un vistazo
df.head(680)
