# -*- coding: utf-8 -*-
"""codigo_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdJgoL0WUQmaptWbZ-JvJ97wPCqoEknV

## Preparación de datos
"""

import altair as alt
import pandas as pd


#cargar datos
df = pd.read_csv("/content/database_masculina_ocupada.csv", sep=";", encoding="latin-1")

# Extraer valor númerico de la categoría Marca
def parse_num(x):
    if pd.isna(x):
        return None
    s=str(x).strip()
    s=s.replace(",", ".")
    cleaned=""
    for c in s:
      if c.isdigit() or c in ".-+":
        cleaned+=c
      else:
        break
    try:
      return float(cleaned)
    except ValueError:
      print("error al convertir valor")
      return None

      df["puntaje"] = df["Marca"].apply(parse_num)

df["puntaje"] = df["Marca"].apply(parse_num)
# Filtrado de filas válidas desde 2019
df = df.dropna(subset=["puntaje", "Año"]).copy()
df = df[df["Año"] >= 2019].copy()
df["Año"] = df["Año"].astype(int)
df["Prueba"] = df["Prueba"].str.strip()


#Echar un vistazo
df.head(250)

"""## Código Base"""

# Control interactivo por tipo de prueba
pruebas_options = sorted(df["Prueba"].dropna().unique().tolist())
prueba_dropdown = alt.binding_select(options=pruebas_options, name="Prueba: ")
prueba_select = alt.selection_point(
    fields=["Prueba"],
    bind=prueba_dropdown,
    value=pruebas_options[0] if pruebas_options else None,
    name="seleccion_prueba"
)

#Selector por clic
click = alt.selection_point(
    fields=["Categoría (grupo)"],
    on="click",
    clear="true"
)
# Normalización categorías a Juvenil/Junior Masculino y Adulto Masculino
def map_categoria(c):
    if isinstance(c, str) and c.strip().lower().startswith("juvenil"):
        return "Juvenil/Junior Masculino"
    return "Adulto Masculino"

df["Categoría (grupo)"] = df["Categoría"].apply(map_categoria)

# Colores de Categoría
fixed_colors = alt.Scale(
    domain=["Juvenil/Junior Masculino", "Adulto Masculino"],
    range=["#d3e6f5", "#01385F"]
)

# Base del gráfico con ejes y tooltips
base = alt.Chart(df).transform_filter(prueba_select).encode(
    alt.X("Año:O", title="Año", sort="ascending", axis=alt.Axis(labelAngle=0)),
    alt.Y("puntaje:Q", title="Marca (m)", axis=alt.Axis(format=".2f")),
    tooltip=[
        alt.Tooltip("Nombre Atleta:N", title="Atleta"),
        alt.Tooltip("Prueba:N", title="Prueba"),
        alt.Tooltip("Categoría (grupo):N", title="Categoría"),
        alt.Tooltip("Competencia:N", title="Competencia"),
        alt.Tooltip("Marca:N", title="Marca"),
        alt.Tooltip("Año:O", title="Año"),
    ],
    detail="Nombre Atleta:N"
)
# Destacador de selección por clic
points = base.mark_point(
    shape="circle", filled=True, size=85
).encode(
    color=alt.Color("Categoría (grupo):N", title="Categoría", scale=fixed_colors),
    opacity=alt.condition(click, alt.value(1), alt.value(0.2))
)

# Gráfico final
chart = points.properties(
    width=160,
    height=200,
    padding=10,
    title="Lanzamiento masculino por categoría entre 2019-2025"
).add_params(
    prueba_select,
    click
).configure_axis(
    labelFontSize=12,
    titleFontSize=12
).configure_legend(
    titleFontSize=13,
    labelFontSize=12,
    orient="bottom",
    labelColor='white',
    titleColor='white'
).configure_view(
    strokeWidth=0,
    fill='black'
).configure(background='#FFFFFF')

chart

"""## Exportar a html y al computador

"""

chart.save("lanzamiento_masculino_2019_2025.html")
from google.colab import files
files.download("lanzamiento_masculino_2019_2025.html")