# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAaMrbI_vQIWqx44zxxERYBapLMC4nfV
"""

import pandas as pd

# Cargar datos con codificación compatible y separador ";"
df = pd.read_csv("/content/drive/MyDrive/Base de datos Mario Pinto.csv",
                 sep=",",
                 encoding="latin-1")

# Echar un vistazo
df.head(112)
