# -*- coding: utf-8 -*-
"""codigo_para_cargar_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q26TOiCWM-o2IuF9O0V42Mj97dY3ESIT
"""

import pandas as pd

#cargar datos
df = pd.read_csv("/content/benjamin-database-limpia.csv", sep=";", encoding="latin-1")
#Echar un vistazo
df.head(65)